# Generated by Django 2.0.7 on 2018-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_college', models.CharField(blank=True, max_length=30)),
                ('target_department', models.CharField(max_length=30)),
                ('no', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('eng_name', models.CharField(max_length=50)),
                ('point', models.IntegerField()),
                ('point_system', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=10)),
                ('quota', models.IntegerField()),
                ('is_FL', models.BooleanField()),
                ('professor', models.CharField(blank=True, max_length=30)),
                ('day_night', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('time_and_location', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
